Add and remove List
karam084/ToDoList pull request #2
Opened 2022-03-30 23:58 UTC by karam084

*- Project requirements

- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
- All changes to the To Do List should be saved in local storage.

2022-03-31 02:24 UTC, keroloussamy requested changes
Hi @karam084, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 02:24 UTC, keroloussamy commented on src/modules/addTask.js
> +}
- [ ] Kindly in your add method you should save the data in the local storage with the three properties `text, completed, index` for every task.
- [ ] Kindly you should when you try to reload the page you have to display the tasks that you have added, from the local storage.

![image](https://user-images.githubusercontent.com/35535130/160962915-0a736c1d-1f41-48f1-b838-1de7b86d05d9.png)

2022-03-31 02:24 UTC, keroloussamy commented on src/modules/deleteTask.js
> +}
- [ ] Kindly in your delete method, you have to remove the task from the tasks array in your local storage, all your tasks will be in an array on the local storage and when you delete a task it should be removed from this array from local storage and from the page also.

![image](https://user-images.githubusercontent.com/35535130/160963247-b2e0f683-5c4e-4d14-b6a1-e4a6af15c62b.png)

2022-03-31 02:24 UTC, keroloussamy commented on src/taskInput.js
> +};
- [ ] Kindly in your edit method, when you edit a task it should be updated on the local storage also, so when you try to reload the page you find the updated data.

2022-04-03 00:29 UTC, CollinsTatang approved these changes
Hi @karam084 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-03 00:41 UTC, merged